version: '3'
services:
  base-workerman:
    build:
      context: ./
      dockerfile: docker-build/workerman/Dockerfile
    container_name: base-workerman
    restart: always
    tty: true
    ports:
      - "12120:2120"
      - "12121:2121"